src/utils.c: suppres unused parameter warning
    utils.c:372:62: error: unused parameter 'completions' [-Werror=unused-parameter]
      372 | getstring_with_completion(char *prompt, const char * const * completions)
          |                                         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~